### ISSUE TITLE
Death to every idiot who uses the stupid 2-letter "titles" when mentioning first names.

### ISSUE THREAD

**Issue by ghost** [itsfoss/text-files#2]
Death to you ItsFOSS monkeys, you cheap loser shills. Death to you for letting that idiot use that disgusting 2 letter racist stupid "title" before his first/surname [on that trashy PPA post].

 Death to you for being such a stupid slave and openly promoting morons who use that disgusting & racist & childish ego "title". Death to you for promoting those stupid childish ego pigs which you openly promote with those silly & disgusting "titles". Death to you ItsFOSSgarbage web losers. You're website is utter trash and run by donkeys. 

Death to you and death to the garbage and useless so called "health" "sector", and every moron who supports that garbage. You're all nothing but worthless slaves. You have no potential, and are a complete and utter laughable failure. Also death to you for making a intro  repo for that "ascii" trash program. Death to every moron who uses that disgusting racist & clownish 3 letter word after "ascii". Death to every idiot who uses the stupid 2-letter "titles" when mentioning first names. Death to "universities" [DUMPSTERversities]. Death to open source. Death to you ItsFOSS linux clowns. Have a sad life and painful death, losers. 

Mechanical Engineering is the ONLY Engineering, period.

Hopefully that loser who used that disgusting 2 letter word before his first/surname will get his throat slit. Burn in agony losers.

**Comment by uciharis** [comment]
what do you mean @ghost ?
